fb_instant_articles.settings:
  type: config_object
  mapping:
    page_id:
      type: string
      label: 'Page ID'
    page_name:
      type: string
      label: 'Page Name'
    style:
      type: string
      label: 'Style'
    ads:
      type: mapping
      label: 'Ads settings'
      mapping:
        type:
          type: string
          label: 'Ad type'
        iframe_url:
          type: uri
          label: 'Ad source URL'
        an_placement_id:
          type: string
          label: 'Audience network placement ID'
        embed_code:
          type: string
          label: 'Ad embed code'
        dimensions:
          type: string
          label: 'Ad dimensions'
    analytics:
      type: mapping
      label: 'Analytics settings'
      mapping:
        embed_code:
          type: string
          label: 'Analytics embed code'
    transformer_logging_level:
      type: string
      label: 'Transformer logging level'
    canonical_url_override:
      type: uri
      label: 'Canonical URL override'
    app_id:
      type: string
      label: 'App ID'
    app_secret:
      type: string
      label: 'App secret'
    access_token:
      type: string
      label: 'Access token'
    page_access_token:
      type: string
      label: 'Page access token'

field.formatter.settings.fbia_ad:
  type: mapping
  label: 'Instant articles ad element formatter settings'
  mapping:
    source_type:
      type: string
      label: 'Source type'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field.formatter.settings.fbia_ad_link:
  type: mapping
  label: 'Instant articles ad element formatter settings'
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field.formatter.settings.fbia_analytics:
  type: mapping
  label: 'Instant articles analytics element formatter settings'
  mapping:
    source_type:
      type: string
      label: 'Source type'

field.formatter.settings.fbia_author_reference:
  type: mapping
  label: 'Instant articles author element formatter settings'
  mapping:
    link:
      type: boolean
      label: 'Link the author'

  field.formatter.settings.fbia_entity_reference_entity_view:
  type: mapping
  label: 'Instant articles rendered entity element formatter settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'

field.formatter.settings.fbia_image:
  type: mapping
  label: 'Instant articles image element formatter settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'
    caption:
      type: boolean
      label: 'Caption'
    presentation:
      type: string
      label: 'Presentation'

field.formatter.settings.fbia_interactive:
  type: mapping
  label: 'Instant articles interactive element formatter settings'
  mapping:
    source_type:
      type: string
      label: 'Source type'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    margin:
      type: string
      label: 'Margin'

field.formatter.settings.fbia_interactive_link:
  type: mapping
  label: 'Instant articles interactive element formatter settings'
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    margin:
      type: string
      label: 'Margin'

field.formatter.settings.fbia_list:
  type: mapping
  label: 'Instant articles list element formatter settings'
  mapping:
    is_ordered:
      type: boolean
      label: 'Ordered list'

field.formatter.settings.fbia_video:
  type: mapping
  label: 'Instant articles video element formatter settings'
  mapping:
    presentation:
      type: string
      label: 'Presentation'
    controls:
      type: boolean
      label: 'Controls'
    autoplay:
      type: boolean
      label: 'Autoplay'
    feed_cover:
      type: boolean
      label: 'Feed cover'
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'

node.type.*.third_party.fb_instant_articles:
  type: mapping
  label: 'Facebook Instant Articles'
  mapping:
    fb_instant_articles_enabled:
      type: boolean
      label: 'Whether to enable Facebook Instant Articles for this content type'
